version: "3"
services:
  Backend:
    build: .
    image: clipapi
    ports:
      - "5001:443"
    environment:
      - App__BackEnd=https://localhost:5001/
      - App__FrontEnd=http://localhost:3000/
      - Google__ServiceMail=
      - Google__ApiKey=
      - Discord__EndPoint=https://discord.com/api
      - Discord__ScopeBot=identify guilds
      - Discord__IdBot=
      - Discord__SecretBot=
      - Discord__TokenBot=
      - Discord__GuildId=
      - Discord__RoleId=
      - Discord__ChannelId=
      - Databases__StandardString=
      - Migration__MigrationString=
      - Migration__ClipsPath=