name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login into registry
      uses: docker/login-action@v1.12.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        # Log out from the Docker registry at the end of a job
        logout: true
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY }}/clip-api:latest
