name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: "./backend"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login into registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ghcr.io/benediktbertsch/clip-backend:latest
  build-frontend:
    defaults:
      run:
        working-directory: "./frontend"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login into registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/benediktbertsch/clip-frontend:latest
